# Generated by Django 5.2.9 on 2025-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntimicrobialPeptide',
            fields=[
                ('apd_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='抗菌肽唯一ID')),
                ('name_class', models.TextField(blank=True, null=True, verbose_name='名称/分类')),
                ('source', models.TextField(blank=True, null=True, verbose_name='来源生物/组织')),
                ('sequence', models.CharField(blank=True, max_length=200, null=True, verbose_name='氨基酸序列')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='序列长度')),
                ('net_charge', models.IntegerField(blank=True, null=True, verbose_name='净电荷')),
                ('hydrophobic_residue_pct', models.CharField(blank=True, max_length=10, null=True, verbose_name='疏水残基百分比')),
                ('boman_index', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='博曼指数')),
                ('three_d_structure', models.CharField(blank=True, max_length=50, null=True, verbose_name='3D结构类型')),
                ('method', models.CharField(blank=True, max_length=20, null=True, verbose_name='测定方法')),
                ('swiss_prot_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='SwissProt ID')),
                ('activity', models.TextField(blank=True, null=True, verbose_name='抗菌活性描述')),
                ('crucial_residues', models.TextField(blank=True, null=True, verbose_name='关键残基信息')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='附加信息')),
                ('title', models.TextField(blank=True, null=True, verbose_name='文献标题')),
                ('author', models.TextField(blank=True, null=True, verbose_name='文献作者')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='文献引用')),
            ],
            options={
                'verbose_name': '抗菌肽数据',
                'verbose_name_plural': '抗菌肽数据表',
                'db_table': 'antimicrobial_peptides',
            },
        ),
    ]
